apiVersion: kubeflow.org/v1beta1
kind: Profile
metadata:
  name: kubeflow
spec:
  owner:
    kind: User
    name: user@example.com
    namespace: test
  {{- if .Values.awsIamForServiceAccount.awsIamRole }}
  plugins:
  - kind: AwsIamForServiceAccount
    spec:
      awsIamRole: '{{ .Values.awsIamForServiceAccount.awsIamRole }}'
      annotateOnly: true
  {{- end }}