apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: <<ROLE_ARN_KUBECONTROLLER>>
  labels:
    kustomize.component: profiles
  name: profiles-controller-service-account
  namespace: kubeflow
